import React, { useState, useEffect } from 'react';
import { 
  ClipboardList, 
  Send, 
  CheckCircle2, 
  Clock, 
  AlertTriangle, 
  ArrowRight, 
  Layers, 
  ShieldCheck, 
  RefreshCw,
  PlusCircle,
  FileText,
  Check,
  ChevronRight,
  Sparkles,
  Globe
} from 'lucide-react';
import { fetchResponsePlans, updatePlanStatus } from '../services/api';

const WORKFLOW_STAGES = ['Approved', 'Deploying', 'In Progress', 'Completed'];

const NEXT_STATUS_MAP = {
  'Approved': 'Deploying',
  'Deploying': 'In Progress',
  'In Progress': 'Completed',
  'Completed': null
};

export default function ResponsePlans() {
  const [plans, setPlans] = useState([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [selectedPlan, setSelectedPlan] = useState(null);
  const [actionMessage, setActionMessage] = useState(null);
  const [updatingStatus, setUpdatingStatus] = useState(false);

  const loadPlans = async (isManualRefresh = false) => {
    if (isManualRefresh) setRefreshing(true);
    else setLoading(true);
    setActionMessage(null);

    try {
      const data = await fetchResponsePlans();
      setPlans(data);
      if (data.length > 0) {
        if (!selectedPlan) {
          setSelectedPlan(data[0]);
        } else {
          // Update selectedPlan with latest version from data
          const updated = data.find(p => p.id === selectedPlan.id || p._id === selectedPlan._id);
          if (updated) setSelectedPlan(updated);
        }
      }
      if (isManualRefresh) {
        setActionMessage({ type: 'success', text: `Successfully refreshed ${data.length} response plans from database.` });
        setTimeout(() => setActionMessage(null), 3000);
      }
    } catch (err) {
      console.error('Failed to load response plans:', err);
      setActionMessage({ type: 'error', text: 'Failed to fetch response plans. Check server connection.' });
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    loadPlans();
  }, []);

  const handleAdvanceWorkflow = async (plan, targetStatus) => {
    const planId = plan.id || plan._id;
    setUpdatingStatus(true);
    setActionMessage(null);

    try {
      const updated = await updatePlanStatus(planId, targetStatus);
      const newStatus = updated.status || targetStatus;

      setPlans(prevPlans =>
        prevPlans.map(p => (p.id === planId || p._id === planId ? { ...p, status: newStatus, workflowState: newStatus } : p))
      );

      if (selectedPlan && (selectedPlan.id === planId || selectedPlan._id === planId)) {
        setSelectedPlan({ ...selectedPlan, status: newStatus, workflowState: newStatus });
      }

      setActionMessage({
        type: 'success',
        text: `Plan ${plan.id || plan.zoneCode} successfully advanced to "${newStatus}".`
      });
      setTimeout(() => setActionMessage(null), 3500);
    } catch (err) {
      console.error('Status update failed:', err);
      setActionMessage({
        type: 'error',
        text: err.message || 'Failed to update workflow state.'
      });
    } finally {
      setUpdatingStatus(false);
    }
  };

  return (
    <div className="p-4 sm:p-6 space-y-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2">
            <h1 className="text-lg sm:text-xl font-mono font-extrabold text-[#F8FAFC] tracking-wider uppercase">
              Emergency Response Orchestration Pipeline
            </h1>
            <span className="px-2 py-0.5 text-[10px] font-mono font-bold bg-[#00F0FF]/15 text-[#00F0FF] border border-[#00F0FF]/40 rounded">
              State Machine v1.0
            </span>
          </div>
          <p className="text-xs text-[#94A3B8] font-mono mt-0.5">
            Sequential multi-stage dispatch manifests generated by SURVER optimization algorithms
          </p>
        </div>

        {/* Refresh Plans Button */}
        <button
          onClick={() => loadPlans(true)}
          disabled={refreshing || loading}
          className="px-4 py-2 cyber-pill disabled:opacity-50 text-[#F8FAFC] rounded-xl text-xs font-mono font-bold flex items-center space-x-2 border border-white/10 transition shrink-0"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${refreshing ? 'animate-spin text-[#00F0FF]' : ''}`} />
          <span>{refreshing ? 'Fetching Plans...' : 'Refresh Plans'}</span>
        </button>
      </div>

      {/* Action Notification Banner */}
      {actionMessage && (
        <div className={`p-3.5 rounded-2xl text-xs font-mono flex items-center space-x-2 backdrop-blur-xl transition shadow-xl ${
          actionMessage.type === 'success'
            ? 'bg-[#10B981]/20 border border-[#10B981]/50 text-[#10B981] shadow-[0_0_15px_rgba(16,185,129,0.2)]'
            : 'bg-[#FF2E54]/20 border border-[#FF2E54]/50 text-[#FF2E54] shadow-[0_0_15px_rgba(255,46,84,0.2)]'
        }`}>
          {actionMessage.type === 'success' ? <CheckCircle2 className="w-4 h-4 text-[#10B981]" /> : <AlertTriangle className="w-4 h-4 text-[#FF2E54]" />}
          <span>{actionMessage.text}</span>
        </div>
      )}

      {/* Main Grid: Plan List (Left) and Detail Manifest (Right) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Plan Cards (5 cols) */}
        <div className="lg:col-span-5 space-y-3">
          <h2 className="text-xs font-mono font-bold uppercase tracking-wider text-[#F8FAFC]">
            Active Orchestration Plans ({plans.length})
          </h2>

          <div className="space-y-2.5 max-h-[600px] overflow-y-auto pr-1 font-mono">
            {plans.map((plan) => {
              const isSelected = selectedPlan?.id === plan.id || selectedPlan?._id === plan._id;
              const currentStatus = plan.status || 'Approved';

              return (
                <div
                  key={plan.id || plan._id}
                  onClick={() => setSelectedPlan(plan)}
                  className={`p-4 rounded-2xl transition cursor-pointer space-y-2.5 ${
                    isSelected
                      ? 'cyber-card border-[#00F0FF] shadow-[0_0_30px_rgba(0,240,255,0.35)] ring-1 ring-[#00F0FF]/50'
                      : 'cyber-card-interactive'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-2">
                      <span className="text-xs font-extrabold text-[#00F0FF] bg-[#00F0FF]/15 px-2.5 py-0.5 rounded-lg border border-[#00F0FF]/40 shadow-sm">
                        {plan.id || 'RP-1024'}
                      </span>
                      <span className="text-xs font-bold text-white uppercase tracking-wide">
                        {plan.zoneCode || 'ZONE'}
                      </span>
                      <span className="text-[10px] text-[#94A3B8]">
                        ({plan.country || 'Global'})
                      </span>
                    </div>

                    <span className={`px-2.5 py-0.5 text-[10px] font-bold rounded-full ${
                      currentStatus === 'Completed' ? 'bg-[#10B981]/20 text-[#10B981] border border-[#10B981]/40 shadow-[0_0_10px_rgba(16,185,129,0.3)]' :
                      currentStatus === 'In Progress' ? 'bg-[#A855F7]/20 text-[#A855F7] border border-[#A855F7]/40 shadow-[0_0_10px_rgba(168,85,247,0.3)] animate-pulse' :
                      currentStatus === 'Deploying' ? 'bg-[#00F0FF]/20 text-[#00F0FF] border border-[#00F0FF]/40 shadow-[0_0_10px_rgba(0,240,255,0.3)] animate-pulse' :
                      'cyber-card text-[#94A3B8] border border-white/10'
                    }`}>
                      ● {currentStatus}
                    </span>
                  </div>

                  <div>
                    <h3 className="text-sm font-bold text-white">{plan.disasterName || 'Emergency Response'}</h3>
                    <div className="flex items-center space-x-3 text-xs text-[#94A3B8] mt-1 font-mono">
                      <span>Type: <strong className="text-[#F8FAFC]">{plan.disasterType || 'Hazard'}</strong></span>
                      <span>Priority: <strong className="text-[#FF2E54] font-bold">{plan.priorityScore}/100</strong></span>
                      <span>Coverage: <strong className="text-[#10B981] font-bold">{plan.coverage || 85}%</strong></span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Right Column: Selected Plan Deep Manifest & Interactive State Machine (7 cols) */}
        <div className="lg:col-span-7">
          {selectedPlan ? (
            <div className="cyber-card rounded-2xl p-6 space-y-6 shadow-2xl relative border border-white/10">
              {/* Header */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-white/10 pb-4 font-mono">
                <div>
                  <div className="flex items-center space-x-2">
                    <span className="text-xs font-extrabold text-[#00F0FF] bg-[#00F0FF]/15 px-3 py-1 rounded-xl border border-[#00F0FF]/40 shadow-[0_0_10px_rgba(0,240,255,0.2)]">
                      {selectedPlan.id || 'RP-1024'}
                    </span>
                    <h2 className="text-base font-bold text-white">
                      {selectedPlan.disasterName}
                    </h2>
                  </div>
                  <p className="text-xs text-[#94A3B8] mt-1">
                    Target Sector: <strong className="text-[#00F0FF] font-bold">{selectedPlan.zoneCode}</strong> | Country: <strong className="text-white">{selectedPlan.country || 'Global'}</strong> | Type: <strong className="text-white">{selectedPlan.disasterType}</strong>
                  </p>
                </div>

                <div className="flex items-center space-x-2">
                  <span className="text-xs text-[#94A3B8] font-mono">Priority Score:</span>
                  <span className="px-3 py-1 bg-[#00F0FF]/15 text-[#00F0FF] font-mono font-extrabold text-xs rounded-xl border border-[#00F0FF]/40 shadow-[0_0_15px_rgba(0,240,255,0.2)]">
                    {selectedPlan.priorityScore}/100
                  </span>
                </div>
              </div>

              {/* WORKFLOW EXECUTION PIPELINE & STATE MACHINE VISUALIZER */}
              <div className="p-4 cyber-card border border-white/10 rounded-2xl space-y-4 shadow-xl font-mono">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-[#F8FAFC] uppercase tracking-wider flex items-center space-x-1.5">
                    <Clock className="w-3.5 h-3.5 text-[#00F0FF]" />
                    <span>Workflow Execution State Machine</span>
                  </span>
                  <span className="text-xs font-bold text-[#00F0FF]">
                    Current Stage: <span className="text-white uppercase font-bold">{selectedPlan.status || 'Approved'}</span>
                  </span>
                </div>

                {/* Visual Step Progress Bar */}
                <div className="grid grid-cols-4 gap-2">
                  {WORKFLOW_STAGES.map((stage, idx) => {
                    const currentIdx = WORKFLOW_STAGES.indexOf(selectedPlan.status || 'Approved');
                    const isCompleted = idx < currentIdx;
                    const isActive = idx === currentIdx;

                    return (
                      <div
                        key={stage}
                        className={`p-2.5 rounded-xl border text-center transition flex flex-col items-center justify-center space-y-1 ${
                          isActive
                            ? 'cyber-pill-active shadow-[0_0_20px_rgba(0,240,255,0.4)] ring-1 ring-[#00F0FF]/50'
                            : isCompleted
                            ? 'bg-[#10B981]/20 text-[#10B981] border-[#10B981]/40'
                            : 'cyber-card text-[#94A3B8] border-white/10'
                        }`}
                      >
                        <div className="flex items-center space-x-1">
                          {isCompleted ? (
                            <Check className="w-3.5 h-3.5 text-[#10B981]" />
                          ) : isActive ? (
                            <span className="w-2 h-2 rounded-full bg-[#00F0FF] animate-ping"></span>
                          ) : (
                            <span className="w-2 h-2 rounded-full bg-white/20"></span>
                          )}
                          <span className="text-[11px] font-bold">
                            {stage}
                          </span>
                        </div>
                        <span className="text-[9px] uppercase font-mono tracking-wider font-semibold">
                          {isActive ? 'ACTIVE' : isCompleted ? 'COMPLETED' : 'PENDING'}
                        </span>
                      </div>
                    );
                  })}
                </div>

                {/* State Machine Transition Action Control */}
                <div className="flex items-center justify-between pt-2 border-t border-white/10">
                  <span className="text-xs text-[#94A3B8]">
                    Next Stage: <strong className="text-[#00F0FF]">{NEXT_STATUS_MAP[selectedPlan.status || 'Approved'] || 'Pipeline Completed'}</strong>
                  </span>

                  {NEXT_STATUS_MAP[selectedPlan.status || 'Approved'] ? (
                    <button
                      onClick={() => handleAdvanceWorkflow(selectedPlan, NEXT_STATUS_MAP[selectedPlan.status || 'Approved'])}
                      disabled={updatingStatus}
                      className="px-5 py-2 cyber-btn-cyan rounded-xl text-xs font-mono font-extrabold flex items-center space-x-1.5 transition"
                    >
                      {updatingStatus ? (
                        <>
                          <span className="w-3.5 h-3.5 border-2 border-[#030712]/30 border-t-[#030712] rounded-full animate-spin"></span>
                          <span>Advancing Workflow...</span>
                        </>
                      ) : (
                        <>
                          <span>Advance to {NEXT_STATUS_MAP[selectedPlan.status || 'Approved']}</span>
                          <ChevronRight className="w-4 h-4" />
                        </>
                      )}
                    </button>
                  ) : (
                    <span className="px-3 py-1.5 bg-[#10B981]/20 text-[#10B981] border border-[#10B981]/40 rounded-xl text-xs font-mono font-bold flex items-center space-x-1 shadow-[0_0_15px_rgba(16,185,129,0.3)]">
                      <CheckCircle2 className="w-3.5 h-3.5 text-[#10B981]" />
                      <span>Response Plan Fully Executed</span>
                    </span>
                  )}
                </div>
              </div>

              {/* Resource Shortages Alert if any */}
              {selectedPlan.shortages && selectedPlan.shortages.length > 0 && (
                <div className="p-4 bg-[#F59E0B]/10 backdrop-blur-xl border border-[#F59E0B]/30 rounded-2xl space-y-2 text-xs shadow-[0_0_20px_rgba(245,158,11,0.15)] font-mono">
                  <div className="flex items-center space-x-2 text-[#F59E0B] font-bold uppercase tracking-wider">
                    <AlertTriangle className="w-4 h-4 text-[#F59E0B]" />
                    <span>Resource Shortage Deficit Flagged</span>
                  </div>
                  {selectedPlan.shortages.map((s, idx) => (
                    <div key={idx} className="flex justify-between bg-[#030712]/60 p-2.5 rounded-xl border border-[#F59E0B]/30 text-[#F8FAFC]">
                      <span><strong>{s.label || s.resourceType}:</strong> Required {s.required} {s.unit}, Allocated {s.availableAllocated} {s.unit}</span>
                      <span className="text-[#FF2E54] font-bold">Deficit: -{s.shortage} {s.unit}</span>
                    </div>
                  ))}
                </div>
              )}

              {/* Dispatch Manifest Table */}
              <div className="space-y-3">
                <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-[#F8FAFC]">
                  Allocated Dispatch Manifest ({selectedPlan.allocations?.length || 0} Assets):
                </h3>

                <div className="space-y-2 max-h-56 overflow-y-auto pr-1 font-mono">
                  {selectedPlan.allocations?.map((item, idx) => (
                    <div
                      key={idx}
                      className="p-3 cyber-card-interactive rounded-xl flex items-center justify-between text-xs"
                    >
                      <div className="space-y-0.5">
                        <div className="font-bold text-white flex items-center space-x-1.5">
                          <span className="text-[#00F0FF] font-bold">{item.quantity} {item.unit}</span>
                          <span className="text-[#F8FAFC]">({item.label || item.resourceType})</span>
                        </div>
                        <div className="text-[11px] text-[#94A3B8]">
                          Origin Depot: <span className="text-[#F8FAFC] font-medium">{item.sourceFacility}</span>
                        </div>
                      </div>

                      <div className="text-right shrink-0 flex items-center space-x-1 text-[#00F0FF] font-mono text-[11px]">
                        <ArrowRight className="w-3 h-3 text-[#94A3B8]" />
                        <span className="font-bold">{selectedPlan.zoneCode}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Explainable Decision Summary */}
              {selectedPlan.explanation && (
                <div className="p-3.5 cyber-card border border-white/10 rounded-2xl space-y-1.5 text-xs text-[#F8FAFC] font-mono">
                  <span className="font-bold text-[#00F0FF] text-[11px] uppercase tracking-wider block">
                    AI Decision Summary:
                  </span>
                  <p className="leading-relaxed text-[#F8FAFC]">{selectedPlan.explanation.summary}</p>
                </div>
              )}
            </div>
          ) : (
            <div className="h-96 rounded-2xl cyber-card border border-dashed border-white/10 flex items-center justify-center text-[#94A3B8] text-xs font-mono">
              Select a response plan from the left to inspect manifest
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
